name: Publish to npm
on:
  push:
    tags: ['v*']
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - name: Validate version matches tag (if tag present)
        shell: bash
        run: |
          PKG_VERSION=$(node -p "require('./package.json').version")
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            TAG_VERSION=${GITHUB_REF#refs/tags/v}
            if [ "$PKG_VERSION" != "$TAG_VERSION" ]; then
              echo "package.json version $PKG_VERSION does not match tag v$TAG_VERSION" >&2
              exit 1
            fi
          fi
      - name: Enforce pre-launch version range (1.2.x only)
        if: startsWith(github.ref, 'refs/tags/')   # ne s’applique que sur un tag
        shell: bash
        run: |
          PKG_VERSION=$(node -p "require('./package.json').version")
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          if [[ ! "$PKG_VERSION" =~ ^1\.2\.[0-9]+$ ]]; then
            echo "Version $PKG_VERSION interdite avant lancement (seules 1.2.x autorisées)" >&2
            exit 1
          fi
          if [[ ! "$TAG_VERSION" =~ ^1\.2\.[0-9]+$ ]]; then
            echo "Tag v$TAG_VERSION interdit avant lancement (seuls v1.2.x autorisés)" >&2
            exit 1
          fi
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
